FROM node:alpine3.18

# Declare build time environment variable
ARG NODE_ENV
ARG POSTGRES_DB_DATABASE_URL

# Set the environment variable
ENV NODE_ENV=$NODE_ENV
ENV POSTGRES_DB_DATABASE_URL=$POSTGRES_DB_DATABASE_URL
ENV AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
ENV AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
ENV AWS_REGION=$AWS_REGION
ENV AWS_BUCKET_NAME=$AWS_BUCKET_NAME

WORKDIR /app
COPY package.json ./
RUN npm install
COPY . .
EXPOSE 4000
CMD ["npm", "run", "start"]